server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 'postgrespw'
    url: jdbc:postgresql://localhost:32768/registration
    username: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop #it drops after rerun
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true